### ISSUE TITLE
可不可以设置图片命名为日期+内容

### ISSUE THREAD

**Issue by lyscop** [lonsty/weibo-image-spider#7]
可不可以设置图片命名为日期+内容

**Comment by lonsty** [comment]
现在没有这个功能哟。

为什么要有这样的需求呢，内容可能会很长，也可能会没有

**Comment by lyscop** [comment]
因为之前一直用53pojie坛友发的新浪微博相册下载工具，用户所有照片是时间+内容命名，很好，因为时间久了，只有图片看不到原微博的内容
![](https://i.imgur.com/5JRWpsN.png)
