### ISSUE TITLE
能不能新增直接用user_id下载的方式

### ISSUE THREAD

**Issue by Sa1koro** [lonsty/weibo-image-spider#8]
微博好像有不允许通过用户名搜索到的设置
还是由于其他什么原因有些用户是无法通过nickname直接搜索到的

这时就会报错" Weibo Structure updated …… " 
能否增加通过直接输入UserID或者主页链接的下载方式

**Comment by lonsty** [comment]
是什么 nickname 不能查到 id，提供下我看看

**Comment by KaminoDice** [comment]
汉青书半霍去病 [https://weibo.com/koplfc0008]

**Comment by lonsty** [comment]
支持使用用户 ID（User ID）下载：python main.py -u USER-ID bdc94df
